export const UPDATE_AMOUNT = 'UPDATE_AMOUNT';
export const ADD_INVESTMENT_OPTION = 'ADD_INVESTMENT_OPTION';
export const DELETE_INVESTMENT_OPTION = 'DELETE_INVESTMENT_OPTION';
export const UPDATE_INVESTMENT_OPTION = 'UPDATE_INVESTMENT_OPTION';
export const UPDATE_PERCENTAGE = 'UPDATE_PERCENTAGE';
export const ROI_TAB_SELECTED = 'ROI_TAB_SELECTED';